repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0 # Release version of Black to be used
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=100
        language_version: python3.10